### ISSUE TITLE
panic: More than 24 cache blocks for one stream element 

### ISSUE THREAD

**Issue by K16DIABLO** [PolyArch/gem-forge-framework#3]
Hello,

I'm still running simulation on your framework, but I faced an error message:
`panic More than 24 cache blocks for one stream element, address (xxxxx) size 1536.`

Why this happens (= Why `dim_vector` cannot be higher than 384?) and how I can fix it? 
Below is the code:
```
const uint64_t dim_vector = 385;
for (uint64_t i = 0; i < 10; i++) {
  for (uint64_t j = 0; j < dim_vector; j++) {
    C[idx[i] + j] = A[idx[i] + j] + B[idx[i] + j];
  }
}
```

Thank you.

**Comment by seanzw** [comment]
Can you check the generated LLVM IR and make sure that the inner loop is not unrolled? So far we can't handle stream with element size too large.

**Comment by K16DIABLO** [comment]
Thanks for your commment!
